=== SvennR/DA-NAN3000-project/NAN/www/test/test1.xsd
<?xml version="1.0" ?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="http://prosjekt.asuscomm.com">

<!-- NESTED VERSION (HIDEOUS!) -->

<xs:element name="GROUPLIST">
<xs:complexType>
    <xs:sequence>
    
    <xs:element name="GROUP" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="purpose" type="xs:string"/>
            <xs:element name="member" minOccurs="0" maxOccurs="unbounded">
            
            <xs:complexType>
                <xs:sequence>    
                    <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fname" type="xs:string"/>
                            <xs:element name="lname" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="role" type="xs:string"/>               
                </xs:sequence>
                <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="course" type="xs:string" use="required"/>
    </xs:complexType>
    </xs:element>
    
    </xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== SvennR/DA-NAN3000-project/NAN/www/test/test1_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="group_list.xsl"?>
<!--DOCTYPE GROUPLIST SYSTEM "test.dtd"-->
<GROUPLIST  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://prosjekt.asuscomm.com test1.xsd">

<GROUP course="FE-BAC3000"> 
    <purpose>Project based learning</purpose>
    
    <member id="001">
        <name>
            <fname>Espen</fname> <lname>Lien Pedersen</lname>
        </name>
        <role>Document handling</role>
    </member>

    <member id="002">
        <name>
            <fname>Glen</fname> <lname>Nordskog</lname>
        </name>
        <role>Quality assurance</role>
    </member>

    <member id="003">
        <name>
            <fname>Svenn</fname> <lname>Rage</lname>
        </name>
        <role>Project leader</role>
    </member>
</GROUP>
<GROUP course="DA-NAN3000">
    <purpose>Network programming</purpose>
    
    <member id="001">
        <name>
            <fname>Espen</fname> <lname>Lien Pedersen</lname>
        </name>
        <role>Coding</role>
    </member>

    <member id="002">
        <name>
            <fname>Glen</fname> <lname>Nordskog</lname>
        </name>
        <role>Coding</role>
    </member>

    <member id="003">
        <name>
            <fname>Svenn</fname> <lname>Rage</lname>
        </name>
        <role>Coding</role>
    </member>
</GROUP>
<GROUP course="None">
    <purpose>No particular purpose</purpose>
    <member id="001">
        <name>
            <fname>Espen</fname> <lname>Lien Pedersen</lname>
        </name>
        <role>Oops</role>
    </member>

    <member id="002">
        <name>
            <fname>Glen</fname> <lname>Nordskog</lname>
        </name>
        <role>Oops</role>
    </member>

    <member id="003">
        <name>
            <fname>Svenn</fname> <lname>Rage</lname>
        </name>
        <role>Oops</role>
    </member>
</GROUP>
</GROUPLIST>
